ParsingStore_App/Models/ParsedProduct.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;

namespace ParsingStore_App.Models
{
    [Table("ParsedProduct")]
    public class ParsedProduct
    {
        public int Id { get; set; }                    
        public string Title { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public byte[] ImageBytes { get; set; }
    }
}

ParsingStore_App/Controllers/ParsePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ParsingStore_App.Models;
using System.Web.Mvc;
using ParsingStore_App.ParserManager;
using ParsingStore_App.DAL;
using System.Net;

namespace ParsingStore_App.Controllers
{
    public class ParsePageController : Controller
    {
        ProductContext dbContext = new ProductContext();
        // GET: ParsePage
        //public ActionResult Index()
        public ActionResult ParsingAction()
        {
            int id = 1;
            SelectList sites = new SelectList(dbContext.Site, "Id", "Name");
            ViewBag.sites = sites;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Site site_ = dbContext.Site.Find(id);
            if (site_ == null)
            {
                return HttpNotFound();
            }
            return View(site_);

            //SelectList products = new SelectList(dbContext.Product, "Id", "ProdName");
            //ViewBag.products = products;

            //return View();
        }

        [HttpPost]
        public ActionResult ParsingAction(Site site)
        {
            string SelectedValue = site.Name;
            return View(site);
            //Request.Form["ddlVendor"].ToString();
            //return View();
        }

        [HttpGet]
        public ActionResult GetProductForParsing()
        {
            ViewModelSiteProduct model = new ViewModelSiteProduct();
            model.allSites = new Site();
            model.allSites.Sites = PopulateSites();
            model.allProducts = new Product();
            model.allProducts.Products = new List<SelectListItem>() { new SelectListItem
                {
                    Text = "choose site",
                    Value = "choose site"
                } };
            //ViewModelSiteProduct vmDemo = new ViewModelSiteProduct();
            //vmDemo.allProducts = dbContext.Product.ToList();
            //vmDemo.allSites = dbContext.Site.ToList();

            return View(model);
        }

        [HttpPost]
        public ActionResult GetProductForParsing(ViewModelSiteProduct site)
        {
            site.allSites.Sites = PopulateSites();
            var selectedItem = site.allSites.Sites.Find(x => x.Value == site.allSites.Id.ToString());
            var v1 = selectedItem.Text;

            List<Product> reesProd = dbContext.Product.ToList().FindAll(x => x.Siteid.ToString() == selectedItem.Value);

            site.allProducts.Products = PopulateProducts(selectedItem.Value);

            //var selectedProd = 

            return View(site);
        }

        [HttpGet]
        public ActionResult GetParsedProduct(ViewModelSiteProduct site)
        {
            ParsedProduct pp = new ParsedProduct() { Id = 1, Title = "testTitle", Price = "5", Description = "testDesc" };
            List<ParsedProduct> listPP = new List<ParsedProduct>();
            listPP.Add(pp);
            return View(listPP);
        }


        private List<SelectListItem> PopulateProducts(string siteID)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            List<Product> reesProd = dbContext.Product.ToList().FindAll(x => x.Siteid.ToString() == siteID);
            foreach (var item in reesProd)
            {
                items.Add(new SelectListItem
                {
                    Text = item.ProdName,
                    Value = item.Id.ToString()
                });
            }

            return items;
        }

        private List<SelectListItem> PopulateSites()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            List<Site> lst = dbContext.Site.ToList();
            foreach (var item in lst)
            {
                items.Add(new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                });
            }

            return items;
        }

        [HttpGet]
        public ActionResult Parse()
        {
            //SelectList
            try
            {
                string strDDLValue = Request.QueryString["SitesList"].ToString();                
                string strDDLValu3 = Request.QueryString["ProductsList"].ToString();
            }
            //SelectList selectList = dbContext.Site.
            catch (Exception ex)
            {

            }

           SelectList sl = new SelectList( dbContext.Site.ToList(), "Id", "Name");
           SelectList pr = new SelectList(dbContext.Product.ToList(), "Id", "ProdName");


            List<SelectListItem> prodList = new List<SelectListItem>()
            {
                 new SelectListItem { Text = "Choose site" },                
            };        

            ViewBag.SitesList = sl;
            ViewBag.ProductsList = pr;

            return View();
        }

        [HttpPost, ActionName("Parse")]
        public ActionResult ParseGetData()
        {
            string strDDLValue1 = null;
            string strDDLValue2 = null;
            // or using QueryString
            try
            {
                strDDLValue1 = Request.Form["SitesList"].ToString();
                strDDLValue2 = Request.Form["ProductsList"].ToString();
            }
            catch (Exception ex) { }

            Site selectedSite = dbContext.Site.ToList().Find(x => x.Id .ToString() == strDDLValue1);
            Product selectedProduct = dbContext.Product.ToList().Find(x => x.Id.ToString() == strDDLValue2);

            ViewBag.Prods = selectedProduct;

            //parse site and populate db
            if ((selectedSite.Name == "badminton.ua") || (selectedProduct.ProdName == "Shoes"))
            {
                IProductXPath prodShoes = new ProductTemaplates.Shoes();
                //string html = HttpService.LoadHTMLPage(selectedSite);

                List<ParsedProduct> psrsedShoesList = ParsingManger.GetProducts(selectedSite, prodShoes);
                foreach(ParsedProduct product in psrsedShoesList)
                {
                    ParsingManger.SaveProductToDB(product, dbContext);
                    dbContext.SaveChanges();
                }               
            }


            return RedirectToAction("ParsedProductTable");
        }

        [HttpGet]
        public ActionResult ParsedProductTable()
        {
            return View(dbContext.ParsedProduct.ToList());
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParsedProduct product = dbContext.ParsedProduct.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

    }
}

ParsingStore_App/Views/ParsePage/Details.cshtml
@model ParsingStore_App.Models.ParsedProduct

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
        </dt>
        <dd>
            @*<img src="@Url.Action(System.Convert.ToBase64String(Model.ImageBytes), "Person", new { id = Model.Id })" alt="Person Image" />*@
            <img src="data:image;base64,@System.Convert.ToBase64String(Model.ImageBytes)" />
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ParsingStore_App/Views/ParsePage/GetParsedProduct.cshtml
@model ParsingStore_App.Models.ParsedProduct

@{
    ViewBag.Title = "GetParsedProduct";
}

<h2>Parsed Products</h2>

<table class="table">
@foreach (var item in Model)
{
    <tr>
        <td>
            @*@if (item.ImageBytes != null)
            {
                <img src="data:image;base64,@System.Convert.ToBase64String(item.ImageBytes)" />
            }*@

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)

        </td>
        <td>            
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.Id })*@
            <br>
            @Html.ActionLink("Details", "Details", new { id = item.Id })                        
        </td>
    </tr>
}
</table>

ParsingStore_App/Views/ParsePage/GetProductForParsing.cshtml
@*@model ParsingStore_App.Models.Site*@
@model ParsingStore_App.DAL.ViewModelSiteProduct

@{
    ViewBag.Title = "GetProductForParsing";
}

<h2>Choose site for parsing</h2>

@using (Html.BeginForm("GetProductForParsing", "ParsePage", FormMethod.Post))
{
    @Html.AntiForgeryToken();    

    @Html.DropDownListFor(Model => Model.allSites.Id, Model.allSites.Sites) 
    //new { @onchange = "CallChangefunc(this.value)" }
    @Html.DropDownListFor(Model => Model.allProducts.Id, Model.allProducts.Products)
    <br>
    <br>
    @*@Html.DropDownListFor(Model => Model.allSites.Id, new SelectList(Model.allSites.Sites, "Id", "Name"));*@
    <br>

    <input type="submit" value="Get enabled products" />
}

@using (Html.BeginForm("GetParsedProduct", "ParsePage", FormMethod.Post))
{  
    <br>
    <input type="submit" value="Start parsing" />
}

<script>
    function CallChangefunc(value) {
        $.post('http://localhost:26811/ParsePage/GetProductForParsing/', { sortBy: value }, function (data) {
            console.log(data)
        })
    }
</script>

  
  

ParsingStore_App/Views/ParsePage/Index.cshtml
@{
    ViewBag.Title = "ParsingAction";
}

<h2>ParsingAction</h2>

ParsingStore_App/Views/ParsePage/Parse.cshtml
@{
    ViewBag.Title = "Parse";
}

<h2>Parse</h2>
@using (Html.BeginForm("Parse", "ParsePage", FormMethod.Post))
    {
            <table>
                <tr>
                    <td> Choose parsing parameters </td>                    
                    </tr>
                <tr>
                    <td>
                        <br>

                        @Html.DropDownList("SitesList", (IEnumerable
                                            <SelectListItem>)ViewBag.SitesList)
                        @*, new { onchange = "form.submit();" }*@

                        @*, new
                        {
                        onchange = "CallChangefunc(this.value);"
                        }*@
                    </td>

                    <td>
                        <br>
                        @Html.DropDownList("ProductsList", (IEnumerable
                        <SelectListItem>)ViewBag.ProductsList)
                    </td>
                </tr>
            </table>
            <br>
            <input type="submit" value="Submit" />
}
<script>
    function CallChangefunc(value) {
        $.post('http://localhost:26811/ParsePage/Parse/', { ProductsList: value }, function (data) {
            console.log(data)
        })
    }
</script>

ParsingStore_App/Views/ParsePage/ParsedProductTable.cshtml
@model IEnumerable <ParsingStore_App.Models.ParsedProduct>

@{
    ViewBag.Title = "ParsedProductTable";
}

<h2>ParsedProductTable</h2>

<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Title)*@
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Description)*@
            Title
        </th>
        <th>
            Description
            @*@Html.DisplayNameFor(model => model.Price)*@
        </th>
        <th>
            Price
            @*@Html.DisplayNameFor(model => model.ImageBytes)*@
        </th>
        <th>
            Options
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.ImageBytes != null)
                {
                    <img src="data:image;base64,@System.Convert.ToBase64String(item.ImageBytes)" />
                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)

            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.ImageBytes)*@
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id=item.Id })*@
                <br>
                @Html.ActionLink("Details", "Details", new { id = item.Id })                                
            </td>
        </tr>
    }
</table>

ParsingStore_App/Views/ParsePage/ParsingAction.cshtml
@model ParsingStore_App.Models.Site


@{
    ViewBag.Title = "ParsingAction";
}

<h2>Parse page</h2>

<p>    
</p>

<p>
@using (Html.BeginForm("ParsingAction", "ParsePage", FormMethod.Post))
{
    @Html.EditorFor(model => model.Sites.Url)

    @Html.DropDownListFor(model => model.Name, ViewBag.Sites as SelectList, new { @onchange = "CallChangefunc(this.value)" })

    <br>
    <input type="submit" value="Send" />
    <br>
    <button name="action" value="add">Start Parsing</button>
}
</p>

<p>
    @*@Html.DropDownListFor(model => model.Name, ViewBag.ProdName as SelectList)*@
</p>

<script>
    function CallChangefunc(value) {
        $.post('http://localhost:26811/ParsePage/ParsingAction/', { sortBy: value }, function (data) {
            console.log(data)
        })
    }
</script>